name: Receipt check
on:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure receipt exists
        run: test -f docs/receipt.latest.json
